version: '3.8'

services:
  # PostgreSQL database for persistent storage
  postgres:
    image: postgres:15-alpine
    container_name: alpaca-postgres
    environment:
      POSTGRES_USER: alpaca
      POSTGRES_PASSWORD: dev_password_change_in_production
      POSTGRES_DB: alpaca_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alpaca"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (price data, indicators)
  redis:
    image: redis:7-alpine
    container_name: alpaca-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
